import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'

const Layout = ({ children, home }) => {
    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-screen px-4 flex flex-col lg:flex-row lg:h-screen 
            bg-amber-100/30'>
                <Navbar />
                <div className='flex-1 overflow-auto py-4 lg:ml-6 mt-4 lg:mt-0'>
                    {children}
                </div>
            </main>
        </div>
    )
}

export default Layout