import React, { useState } from 'react'
import Head from 'next/head'
import Navbar from './Navbar'

import { BiMenu } from 'react-icons/bi'
import { IoMdClose } from 'react-icons/io'
import Intro from './Intro'
import Footer from './Footer'

const Layout = ({ children, mainPage }) => {
    const [menu, setMenu] = useState(false);

    const handleToggleMenu = () => {
        setMenu(prevState => !prevState);
    }

    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-screen px-4 lg:px-8 lg:h-screen min-h-screen lg:min-h-auto
            bg-gradient-to-r from-amber-400'>

                {menu ?
                    (<IoMdClose
                        size={30}
                        className='fixed right-1 top-1 cursor-pointer lg:hidden z-20'
                        onClick={handleToggleMenu}
                    />)
                    :
                    (<BiMenu
                        size={30}
                        className='fixed right-1 top-1 cursor-pointer lg:hidden z-20'
                        onClick={handleToggleMenu}
                    />)
                }

                <Navbar open={menu} />

                <div className={`flex lg:flex-row py-4 w-full max-h-full 
                ${mainPage ? 'flex-col' : 'flex-col-reverse'}`}>
                    <Intro />

                    {!mainPage && <hr className='my-4 '/>}
                    
                    <div className='flex-1 overflow-auto lg:ml-6 mt-4 lg:mt-0'>
                        {children}
                    </div>
                </div>

                <Footer />

            </main>
        </div>
    )
}

export default Layout